### ISSUE TITLE
Color picker only showing when I reload the page

### ISSUE THREAD

**Issue by aussiDavid** [kostia/jquery-minicolors-rails#21]
I have installed the gem and followed the simple form example of the homepage.

        <div class="row">
          <div class="col-md-6">
            <div class="form-group"><%= f.input :color_theme_1, label: "Color Theme 1", as: :minicolors, input_html: {data: { minicolors: {theme: :bootstrap, position: :right}}} %></div>
          </div>
          <div class="col-md-6">
            <div class="form-group"><%= f.input :color_theme_2, label: "Color Theme 2", as: :minicolors, input_html: {data: { minicolors: {theme: :bootstrap, position: :right}}} %></div>
          </div>
        </div>

Here is one of the links that I use to get to the page with the color picker

     <%= link_to "Update Account Information", edit_account_path(@account), class: 'btn btn-default top-20' %>

When I click on a link like the above, the color pickers to do not appear. If I manually reload the page the color pickers appear and work correctly.

Any idea's as to what's going on?

**Comment by kostia** [comment]
Do you have Turbolinks enabled?

**Comment by aussiDavid** [comment]
Yes.

**Comment by kostia** [comment]
The bootstrap script for the simple form integration does not work with Turbolinks.

As you can see in https://github.com/kostia/jquery-minicolors-rails/blob/master/vendor/assets/javascripts/jquery.minicolors.simple_form.js it listens to `domready` event using jQuery, which Turbolinks prevents to be triggered, because the document stays the same between the page views, but only its body is replaced. Thus, you can quick fix that by using an adopted bootstrap script (I did not check if it works, but it should):

```javascript
var bootstrapColorpicker = function() {
  $('[data-minicolors]').each(function(i, elem) {
    var input = $(this);
    input.minicolors(input.data('minicolors'));
  });
};

$(bootstrapColorpicker);
$(document).on('page:load', bootstrapColorpicker);
```

Since I generally don't use Turbolinks for many reasons (and encourage everybody to do so too), I did not build any workarounds for the case the app does use Turbolinks. You're welcome to create a pull-request using the above workaround :smile:

**Comment by kostia** [comment]
I've created a wish for Turbolinks support, which I plan to add in the next version.

**Comment by aussiDavid** [comment]
thank you.
